name: Deploy File to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 65.0.180.87 >> ~/.ssh/known_hosts

      - name: Upload file to EC2
        run: scp -i ec2_key.pem ./yourfile.txt $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/
        env:
          EC2_HOST: 65.0.180.87
          EC2_USERNAME: ubuntu
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}