name: Deploy File to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          echo "$EC2_PRIVATE_KEY" > LostKey.pem
          chmod 600 LostKey.pem

      - name: Upload file to EC2
        run: scp -i LostKey.pem ./yourfile.txt $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/
        env:
          EC2_HOST: 65.0.180.87
          EC2_USERNAME: ubuntu
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
